version: '3'

services:
  api: &api
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: project-d-api
    env_file:
      - ./.env
    volumes:
      - ./app:/code/app
    ports:
      - "80:80"
